
import fetch from 'node-fetch';

const WORKER_URL = 'https://aigroup-mdtoword-mcp.jackdark425.workers.dev/mcp';

async function testDeployedWorker() {
    console.log(`Testing deployed worker at: ${WORKER_URL}`);

    const payload = {
        jsonrpc: '2.0',
        id: 'test-deploy-1',
        method: 'tools/call',
        params: {
            name: 'markdown_to_docx',
            arguments: {
                markdown: '# Deployed Test\n\nThis document was generated by the deployed Cloudflare Worker.',
                filename: 'deployed_test.docx'
            }
        }
    };

    try {
        const response = await fetch(WORKER_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status} ${response.statusText}`);
        }

        const data = await response.json();
        console.log('Response received:');

        if ((data as any).result && (data as any).result.content) {
            const content = (data as any).result.content;
            console.log('✅ Success! Message:', content[0]?.text);

            const structured = (data as any).result.structuredContent;
            if (structured) {
                console.log(`📄 Generated file size: ${structured.size} bytes`);
                if (structured.content) {
                    const fs = await import('fs/promises');
                    const buffer = Buffer.from(structured.content);
                    await fs.writeFile('deployed_test.docx', buffer);
                    console.log('💾 Saved to deployed_test.docx');
                }
            }
        } else {
            console.log('Response data:', JSON.stringify(data, null, 2));
        }

    } catch (error) {
        console.error('❌ Test failed:', error);
    }
}

testDeployedWorker();
